---
version: '3.9'

services:
  doh-proxy:
    image: ghcr.io/jacobwoffenden/doh-proxy:latest
    environment:
      - PROVIDER=cloudflare-zero-trust
      # e.g. if your Cloudflare Zero Trust URL is https://abcdefghij.cloudflare-gateway.com/dns-query, the CLOUDFLARE_ZERO_TRUST_ID is abcdefghij
      - CLOUDFLARE_ZERO_TRUST_ID=replace-me
    ports:
      - '53:53/udp'
