---
name: "Build Image"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "amd64", "arm64", "386", "arm/v7", arm/v6 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Build Arguments
        id: prepare_build_args
        run: |
          echo ::set-output name=build_created::$( date --utc +"%Y-%m-%dT%H:%M:%SZ" )
          echo ::set-output name=build_version::$( echo "${{ github.sha }}" )
          echo ::set-output name=build_revision::$( echo "${{ github.sha }}" )

      - name: Set up QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Container
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          load: true
          tags: |
            doh-proxy:latest
          build-args: |
            BUILD_CREATED=${{ steps.prepare_build_args.outputs.build_created }}
            BUILD_VERSION=${{ steps.prepare_build_args.outputs.build_version }}
            BUILD_REVISION=${{ steps.prepare_build_args.outputs.build_revision }}

      - name: Test cloudflared
        id: test_cloudflared
        run: |
          docker run --rm --entrypoint /usr/local/bin/cloudflared doh-proxy:latest version

      - name: Anchore Scan
        id: anchore_scan
        uses: anchore/scan-action@v3
        with:
          image: doh-proxy:latest
          fail-build: false
          severity-cutoff: critical
          acs-report-enable: true

      - name: Upload Anchore Scan SARIF report
        id: upload_anchore_scan_serif_report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      # - name: Snyk Scan
      #   id: snyk_scan
      #   continue-on-error: true
      #   uses: snyk/actions/docker@0.3.0
      #   with:
      #     image: doh-proxy:latest
      #     args: --file=Dockerfile
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # - name: Upload Snyk Scan SARIF report
      #   id: upload_snyk_scan_serif_report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif

      - name: Trivy Scan
        id: trivy_scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: doh-proxy:latest
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy Scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif