---
name: Build and Push Latest

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  build-push-latest:
    name: Build and Push Latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Prepare Environment
        id: prepare_environment
        run: |
          echo "build_created=$( date --utc +"%Y-%m-%dT%H:%M:%SZ" )" >> "${GITHUB_ENV}"
          echo "build_version=latest" >> "${GITHUB_ENV}"
          echo "build_revision=$( echo "${{ github.sha }}" )" >> "${GITHUB_ENV}"
          echo "cloudflared_version=$( curl --silent https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name' )" >> "${GITHUB_ENV}"

      - name: Install ORAS CLI
        id: install_oras
        run: |
          orasVersion=$( curl --silent https://api.github.com/repos/oras-project/oras/releases/latest | jq -r '.tag_name' | sed 's/v//' )
          export orasVersion
          curl -LO https://github.com/oras-project/oras/releases/download/v"${orasVersion}"/oras_"${orasVersion}"_linux_amd64.tar.gz
          tar -zxvf oras_"${orasVersion}"_linux_amd64.tar.gz
          rm -f oras_"${orasVersion}"_linux_amd64.tar.gz LICENSE

      - name: Install Sigstore Cosign
        id: install_cosign
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 # v3.0.5

      - name: Set up Docker QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2.6.0

      - name: Login to GitHub Container Registry
        id: ghcr_login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry (ORAS)
        id: oras_ghcr_login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build and Publish Containers to GitHub Container Registry
        id: build_publish
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ghcr.io/jacobwoffenden/doh-proxy:${{ env.build_version }}
          build-args: |
            BUILD_CREATED=${{ env.build_created }}
            BUILD_VERSION=${{ env.build_version }}
            BUILD_REVISION=${{ env.build_revision }}
            CLOUDFLARED_VERSION=${{ env.cloudflared_version }}

      - name: Sign Containers
        id: sign_containers
        run: |
          cosign sign --recursive ghcr.io/jacobwoffenden/doh-proxy:${{ env.build_version }}
        env:
          COSIGN_EXPERIMENTAL: 1
          
      - name: Verify Containers
        id: verify_containers
        run: |
          cosign verify ghcr.io/jacobwoffenden/doh-proxy:${{ env.build_version }}
        env:
          COSIGN_EXPERIMENTAL: 1
