---
name: "Scheduled Image Scan"

on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trivy Scan
        id: trivy_scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: ghcr.io/jacobwoffenden/doh-proxy:latest
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy Scan SARIF report
        id: upload_trivy_sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
