---
name: Scheduled Image Scan

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  scheduled-image-scan:
    name: Scheduled Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Trivy Scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@0cd397afbfae6b60e8061fda662f3511aa5d054e # v0.11.1
        continue-on-error: true
        with:
          image-ref: ghcr.io/jacobwoffenden/doh-proxy:latest
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy Scan SARIF report
        id: upload_trivy_sarif
        uses: github/codeql-action/upload-sarif@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2.3.6
        with:
          sarif_file: trivy-results.sarif
