---
name: "Run Tests"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        id: hadolint

  test-providers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Provider Tests
        id: test
        run: |
          sudo apt install --yes dnsutils
          bash -x scripts/provider-test.sh
        env:
          CLOUDFLARE_ZERO_TRUST_ID: ${{ secrets.CLOUDFLARE_ZERO_TRUST_ID }}
          NEXTDNS_ID: ${{ secrets.NEXTDNS_ID }}
        

